input_modality_channels:
  - 256
  - 35
output_dim:
  - 1
d_model: 40
n_heads: 8
n_layers: 6
dropout_embedding: 0.
dropout_relu: 0.1
dropout_residual: 0.1
dropout_output: 0
module_ffn_fusion: True

attention_type: linear