input_modality_channels:
  - 25
  - 35
  - 256
output_dim:
  - 5
d_model: 40
n_heads: 8
n_layers: 6
dropout_embedding: 0.
dropout_relu: 0.1
dropout_residual: 0.1
dropout_output: 0

multimodal_signal_type: gap
multimodal_signal_time_dim: 450
module_time_reduce: gap

attention_type: bigbird
block_size: 64
num_global_tokens: 16
num_random_tokens: 10
dropout_attention: 0.